Fix MacOSX cmake missing symbol _clock_gettime
On El Capitan:
     [exec] [100%] Linking C executable openssl
     [exec] Undefined symbols for architecture x86_64:
     [exec]   "_clock_gettime", referenced from:
     [exec]       _app_timer_real in apps_posix.c.o
     [exec] ld: symbol(s) not found for architecture x86_64
     [exec] clang: error: linker command failed with exit code 1 (use -v to see invocation)
     [exec] make[2]: *** [apps/openssl/openssl] Error 1
     [exec] make[1]: *** [apps/openssl/CMakeFiles/openssl.dir/all] Error 2
     [exec] make: *** [all] Error 2